### ISSUE TITLE
error when piping to ccat.py

### ISSUE THREAD

**Issue by 400thecat** [welbornprod/ccat#1]
I can ccat a file directly:

    ccat.py file.log

buy I get an error when piping to ccat.py"

    tail file.log | ccat.py

or even the basic usage example :

    echo "import os" | ccat.py

The errors I get:

    Traceback (most recent call last):
      File "/usr/local/bin/ccat.py", line 1044, in <module>
        mainret = main(docopt.docopt(USAGESTR, version=VERSIONSTR))
      File "/usr/local/bin/ccat.py", line 100, in main
        return 0 if (print_files(config) and save_config(config)) else 1
      File "/usr/local/bin/ccat.py", line 446, in print_files
        if not set_lexer(filename, config):
      File "/usr/local/bin/ccat.py", line 634, in set_lexer
        ext = os.path.splitext(filename)[-1].lower()
      File "/usr/lib/python3.7/posixpath.py", line 122, in splitext
        p = os.fspath(p)
    TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by cjwelborn** [comment]
Hmm, I pipe to ccat a lot. I'll have to check it out.

**Comment by cjwelborn** [comment]
@400thecat, yeh I introduced a bug when I created "configurable file-extension-based lexers" (for languages that are not always recognized by pygments, like .vim and .json). Should be fixed now.
